### ISSUE TITLE
utf8 Encoding Problem with german umlauts

### ISSUE THREAD

**Issue by ihateaccountssomuch** [pfitzer/kunena-discord#1]
Hello!
I has tesed you Plugin it works, that it Posts Messages into Discord, but when a umlaut in the Kunea Toppic was included, then its broken:
![grafik](https://user-images.githubusercontent.com/62882636/77905023-d94adb80-7285-11ea-9ad6-ac62b702c450.png)

The Issue was tested under Discord Desktop; Discord Web; Discord Android.

**Comment by pfitzer** [comment]
is fixed and will be deployed with version 1.1.3 maybe today. I wanna take a look on your other issue first ;)
