### ISSUE TITLE
Link wrong, when Joomla is not in the root directory installed.

### ISSUE THREAD

**Issue by ihateaccountssomuch** [pfitzer/kunena-discord#2]
Hello, i have the Issue, that my Joomla Page is installed in a subfolder named /mainpage.
The Link the Bot generates, duplicates the word /mainpage.

Bot Link:
https://example.de//mainpage/mainpage/index.php/forum/ankuendigungen/251-themen-fuer-das-naechste-gespraech/6034#6034

Correct Link:
https://example.de//mainpage/index.php/forum/ankuendigungen/251-themen-fuer-das-naechste-gespraech/6034#6034

I have a 302 Redirect in my root folder in the moment, who redirects automaticly into /mainpage.
Could this be causing the issue?

**Comment by pfitzer** [comment]
Wir machen mal auf Deutsch weiter hätte ich gesagt. Das kann schon sein das es am redirect liegt. Kann ich im Moment nicht nachstellen, da ich keine solche Installation habe. Und keinen Apache, wenn ich mit meiner Vermutung richtig liege.

Ich bleib da aber dran und bau mir mal sowas zusammen, kann aber ein wenig dauern, hab viel um die Ohren im Moment.

Vielleicht kannst du mir mal noch den redirect Teil angeben damit ich das genauso mache.

**Comment by ihateaccountssomuch** [comment]
Ich stelle fest, es ist garkeine 302 weiterleitung, da unterlag ich leider einem Trugschluss.

Das macht eine index.php:
`<?php
header('Location: https://example.de/mainpage/');
exit;
?>`

**Comment by pfitzer** [comment]
Alles klar, schau ich mir mal an die Tage.

**Comment by nightw0lv** [comment]
I have the same problem and I dont know German.

**Comment by nightw0lv** [comment]
bot
https://website.com/forum/main/main-forum/10-general-discussion/list.html?general=gaming-discussions#12
normal
https://website.com/forum/main/general-gaming-discussions/10-general-discussion.html

fixed doing this
http://prntscr.com/rxgaku

**Comment by pfitzer** [comment]
Added a new config param for website url

![discord](https://user-images.githubusercontent.com/1109410/79227376-14413780-7e60-11ea-98d5-d907de6c6c84.png)
