### ISSUE TITLE
add french language

### ISSUE THREAD

**Issue by yohji79** [pfitzer/kunena-discord#6]
hello, 
I made translation, how can I put it in ?

**Comment by pfitzer** [comment]
You can do it with a [pull request](https://help.github.com/en/enterprise/2.16/user/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) or you mail me the files: michael@mp-development.de

thx for contributing

**Comment by yohji79** [comment]
[fr-FR.zip](https://github.com/pfitzer/kunena-discord/files/4504960/fr-FR.zip)

Here files in french :)

**Comment by pfitzer** [comment]
Ok v1.3.0 with french translations is online.

thx

**Comment by yohji79** [comment]
Sorry, a bad letter in te file fr-FR.plg_kuenena_discord.ini

line 9 
PLG_KUNENA_DISCORD_MESSAGE_NEW="Un nouveau sujet da**n**s votre forum." 

perhaps it could be better to have the topic in bold instead of the new thread info.

thank you.

**Comment by pfitzer** [comment]
That`s maybe not a bad idea, i`ll give it a try.

**Comment by pfitzer** [comment]
Looks good, nice one ;)
